Add option for inlining styles for table borders
lblod/ember-rdfa-editor pull request #1142
Opened 2024-02-15 15:22 UTC by piemonkey

### Overview
Allows control of table border styles by (dev) users of the editor. When no style is passed, it defaults to the current behaviour, which is the CSS applies a border in the editor but this is not serialized/exported. If a style is passed, it's serialized.

##### connected issues and PRs:
PR to embeddable to expose this tbc.

### Setup
Inlined styles can be tweaked in the schema for test pages of the dummy app.

### How to test/reproduce
Create a table and see the border styles are applied correctly and then click 'show export preview' or copy-paste it into e.g. google docs. With no style passed, behaviour should be unchanged, i.e. thin border in the editor, nothing in the copy-pasted content.

### Challenges/uncertainties
N/A

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-02-19 10:28 UTC, elpoelma requested changes
Looks good overall, table is now correctly exported with inline styles. I just have some questions on the `table` node-view.

2024-02-19 10:28 UTC, elpoelma commented on addon/plugins/table/index.ts
> +    }
It seems we now both define the border-styles in inline css **and** external css for the dynamic table view. We can probably remove the external css on tables **or** not apply the border inline-css to the dynamic node-view.

2024-02-19 10:28 UTC, elpoelma commented on addon/plugins/table/index.ts
> +    }
I don't know if we necessarily want this, as table `attrs` will not always be valid html attributes.

2024-02-22 17:28 UTC, elpoelma approved these changes

2024-02-22 19:25 UTC, abeforgit approved these changes

2024-02-22 19:29 UTC, merged