GN-4723: Addition of `table-tooltip` component allowing users quick access to table-editing features
lblod/ember-rdfa-editor pull request #1144
Opened 2024-02-19 13:13 UTC by elpoelma

### Overview
This PR includes several changes leading into the implementation of a `table-tooltip` component. This component allows users quick access to table-editing features.
Specifically, this PR includes the following changes/features:
- Addition of the `floating-ui` package and implementation of a custom (for now private) `floating-ui` modifier. Compared to the modifier provided by the `ember-velcro` package, it includes the following features:
   * Support for virtual elements (https://floating-ui.com/docs/virtual-elements)
   * Support for transform positioning (similar to the `vue` and `react` implementations of `floating-ui`: https://floating-ui.com/docs/usefloating#transform). By default the modifier uses `transform` positioning, but this can be disabled.
   * Support for fully customizable middleware-pipelines
- Addition of a (private) `selection-tooltip` component. This is a simple tooltip which displays under the current editor selection. It does so by leveraging the `floating-ui` modifier in combination with usage of virtual elements. A virtual element is used here, as the editor selection does not (always) correspond to a specific element, but rather to a position/series of positions. https://floating-ui.com/docs/virtual-elements contains more information on how to use virtual elements
- Addition of a (public) `table-tooltip` component. A simple tooltip which displays only when inside a table. It provides several table-actions including:
  * Add row after
  * Add row before
  * Add column after
  * Add column before
  * Delete row
  * Delete column
  * Delete table
  This tooltip is implemented to be as non-intrusive as possible: it only displays when clicking; and disappears when typing.

##### connected issues and PRs:
[GN-4723](https://binnenland.atlassian.net/browse/GN-4723?atlOrigin=eyJpIjoiMmVjNzhmNTc2ZDZhNGI2M2FkNGZmNWVkZDU2MjM1NDgiLCJwIjoiaiJ9)

### How to test/reproduce
- Open the dummy app on the `home` page
- Insert a table with some content inside
- Clicking inside any cell, the table-tooltip should appear
- The different actions provided by the table-tooltip should work
- When scrolling the viewport, the tooltip should correctly move along with the selection
- The tooltip should correctly disappear when the selection is out-of-view. (This is why the `contextElement` of the virtual-element is needed)
- When starting to type in the cell, the tooltip should disappear
- Observe that the tooltip element uses `transform` based positioning and the `position: fixed` approach.

### Challenges/uncertainties
- I did not opt into using the `ember-velcro` package for the implementation of this tooltip as it is missing several needed features. We might be able to upstream some features (such as virtual-element support and transform-based position) in the future.

### TODOs/Future work
- [x] Add `toggle header row` and `toggle header column` actions to tooltip
- [x] (Optional) Look into using a grid layout for the table-tooltip
- [ ] Look into supporting the `arrow` middleware (https://floating-ui.com/docs/arrow) (not crucial for this PR)
- [ ] Look into supporting a 'headless' version of the `floating-ui` modifier, in which the user itself has more control over how the styling is set/computed. (see the https://floating-ui.com/docs/vue and https://floating-ui.com/docs/react packages) (not crucial for this PR)
- [ ] Replace usages of `ember-velcro` with our custom `floating-ui` modifier (not crucial for this PR)
- [ ] Apply `size` modifier to dropdown components => allows for displaying a scrollbar when viewport is too short.

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-02-21 18:05 UTC, abeforgit commented
small detail: the column resize handle renders above the popup, otherwise nice work!

2024-02-21 18:06 UTC, abeforgit requested changes
small detail: the column resize handle renders above the popup, otherwise nice work!

2024-02-22 09:29 UTC, elpoelma commented
> small detail: the column resize handle renders above the popup, otherwise nice work!

Nice catch, thanks! This should be solved. It seems the `z-index` css rule of the `resize-handle` is not really necessary.

2024-02-22 19:04 UTC, abeforgit approved these changes

2024-02-22 19:14 UTC, merged