GN-4706: Table cell background
lblod/ember-rdfa-editor pull request #1162
Opened 2024-03-14 10:20 UTC by dkozickis

### Overview

##### connected issues and PRs:

Closes #1161 

### Setup

1. Checkout

### How to test/reproduce

Repeat after me:

https://github.com/lblod/ember-rdfa-editor/assets/769698/50bd46eb-4b5c-41b4-8219-2f059a93e457

### Challenges/uncertainties

Design 😅 

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows

Uploading CleanShot 2024-03-14 at 12.21.26.mp4…

- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-03-14 11:08 UTC, piemonkey approved these changes
Looks good. I feel like having both the toolbar button and the color choice in the (very aggressive in my view) tooltip menu seems like too much, but maybe that's just me.

2024-03-14 11:37 UTC, elpoelma requested changes
Works well overall, just some remarks.

- We should (as you mentioned) review the design.
- We should probably also use a different icon to avoid confusion.
- I'm wondering if it is possible to include the color picker in the floating tooltip?

2024-03-14 11:37 UTC, elpoelma commented on addon/components/plugins/table/color.hbs
> +        title={{t 'ember-rdfa-editor.color.button-label'}}
We should use another label for this.

2024-03-14 11:37 UTC, elpoelma commented on addon/components/plugins/table/color.ts
I'm wondering if we should include a seperate dropdown button, like we use for the highlight toolbar button.
This way the user can use between quickly applying a color and selecting a different color.
Not sure what the best approach would be here.

2024-03-14 11:37 UTC, elpoelma commented on addon/plugins/table/nodes/table.ts
> +    },
Nice approach to include seperate `fromDOM` and `toDOM` methods for each of the attributes. I was already thinking of including that option in the default `SayNodeSpec` API.

2024-03-15 11:34 UTC, abeforgit commented
> Looks good. I feel like having both the toolbar button and the color choice in the (very aggressive in my view) tooltip menu seems like too much, but maybe that's just me.

having both is indeed much, I think in apps we'd have either/or though
for the tooltip menu I agree its a bit in your face atm. You have ideas on how to improve it? maybe moving it a bit further away from the cursor would already help?

2024-03-15 12:12 UTC, abeforgit reviewed
Don't really know how to solve this, but if you select multiple cells, the selection color overrides the background color, so it kinda seems like the cell color feature isn't doing anything (until you deselect)

If you know of a quick solution, it would be nice (maybe something with the alpha channel on css `rgba()` colors? or some opacity setting?)

2024-03-19 15:56 UTC, abeforgit approved these changes

2024-03-24 14:44 UTC, merged