Internal/standarization and classes rework
lblod/ember-rdfa-editor pull request #1231
Opened 2024-11-21 10:25 UTC by lagartoverde

### Overview
First part of the standarization ticket, add a class to every node that can be changed by the user and document how.

##### connected issues and PRs:
GN-4644

### Setup
None

### How to test/reproduce
Mostly a review of API, but you can add classes to the different nodes and check that they get applied, also you can add styles to the existing classes

### Challenges/uncertainties
None

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check cancel/go-back flows
- [ ] Check database state correct when deleting/updating (especially regarding relationships)
- [ ] changelog
- [ ] npm lint
- [ ] no new deprecations

2024-11-21 13:44 UTC, elpoelma reviewed
Really nice work, I do have some (pedantic) comments.

On the `classNames` attribute/setting:
- Maybe add it to the `SayNodeSpec` type
- Maybe we could extend its type to `string[] | (node: PNode) => string[]`. This allows for dynamic configurations.

2024-11-21 13:44 UTC, elpoelma commented on README.md
> +| ListItem | say-li |
As all others classnames are written in full, maybe we could also use `say-list-item` here? Really pedantic I know.

2024-11-21 13:44 UTC, elpoelma commented on app/styles/ember-rdfa-editor/_c-content.scss
>    div,
Would it be possible to replace this `div` by e.g. `.say-block-rdfa`. This way that rule would be less general, and wouldn't target unwanted elements.

2024-11-21 14:44 UTC, lagartoverde commented
> * string[] | (node: PNode) => string[]

pedantic review is just what I was looking for, this is an API change so it should be as good as possible :)
What would the function approach solve that we don't solve with the array?

2024-11-21 14:47 UTC, lagartoverde commented
And about adding it to the SayNodeSpec @abeforgit said something against it, don't remember what it was, I think something about not forcing the plugin creators to add it

2024-11-22 08:31 UTC, elpoelma commented
> > * string[] | (node: PNode) => string[]
> 
> pedantic review is just what I was looking for, this is an API change so it should be as good as possible :) What would the function approach solve that we don't solve with the array?

So for historical reference: it would allow node-specs to define dynamic classes which depend on e.g. attribute values.

2024-11-22 08:31 UTC, elpoelma commented
> And about adding it to the SayNodeSpec @abeforgit said something against it, don't remember what it was, I think something about not forcing the plugin creators to add it. But not sure why it can't be an optional attribute

Yeah I'd make it optional indeed.

2024-11-25 13:45 UTC, elpoelma requested changes
Looks sane code-wise.
- There are still some failing tests
- I would maybe wait with merging this until we see the effects on the editor-plugins and GN

2024-12-18 07:54 UTC, merged