Fix document RDFa extractor to get subject attributes
lblod/ember-rdfa-editor pull request #1233
Opened 2024-12-03 16:29 UTC by piemonkey

### Overview
Currently causes RB to crash when attempting to save new regulatory statement templates as they have properties but no subject.

##### connected issues and PRs:
N/A

### Setup
I tested linked to RB.

### How to test/reproduce
Create a new blank regulatory statement template in RB and then save it. It should save and not crash.

### Challenges/uncertainties
N/A

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check cancel/go-back flows
- [ ] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-12-05 13:41 UTC, elpoelma requested changes
This makes sense, but shouldn't we do the `node.dataset['subject']` check seperate from the `node.dataset['outgoingProps']`. This way we also support nodes with a subject but without outgoing props. Similar to the original `getRdfaAwareAttrs`.
Wouldn't it also be possible to check on the `node.dataset['rdfaNodeType']` attribute, similar to `getRdfaAwareAttrs`?

2024-12-10 10:15 UTC, piemonkey commented
> This makes sense, but shouldn't we do the `node.dataset['subject']` check seperate from the `node.dataset['outgoingProps']`. This way we also support nodes with a subject but without outgoing props. Similar to the original `getRdfaAwareAttrs`. Wouldn't it also be possible to check on the `node.dataset['rdfaNodeType']` attribute, similar to `getRdfaAwareAttrs`?

You're right about making the subject check separate. I've changed that now. For the rdfaNodeType, I don't think we currently set a node type for documents, so I don't think this works here. Did you have something else in mind?

2024-12-10 10:40 UTC, abeforgit commented
yeah we dont set the rdfaNodeType for documents
I tried to set that always to resource, but it caused other issues
so the doc node is being special cased in all the parsing logic atm

2024-12-10 14:54 UTC, abeforgit approved these changes
lgtm

2024-12-10 15:47 UTC, merged