Copy command
lblod/ember-rdfa-editor pull request #140
Opened 2021-07-30 14:28 UTC by RobbeDP

As mentioned in #132, most of the code of the cut command could be reused in order to implement the copy command. This is what I did here.

I made a copy handler, which makes use of a variation of the `DeleteSelectionCommand` named `ReadSelectionCommand`. This command doesn't actually delete the nodes in the provided range, but just returns them. Also the split that is performed on the VDOM is not actually written back to the DOM.

To restore the VDOM to its state before the split was performed, I tried to implemented some sort of VDOM history, which we can later on use to implement a better undo command.

On this undo I'm a bit stuck now. I'm able to restore the VDOM, but when I try to also write back this VDOM restoration to the actual DOM, the appendChild in `html-writer.ts` doesn't actually append anything. I can't seem to figure out why.

2021-08-05 13:21 UTC, abeforgit requested changes
Works well on the surface, but we can't merge this yet because non-command document edits such as backspace don't create a snapshot, and are skipped over when undoing

2021-08-08 13:17 UTC, RobbeDP commented
This PR now only contains the changes that introduce the copy command. The model undo has been moved to #143.

2021-08-31 16:30 UTC, abeforgit approved these changes

2021-09-01 15:15 UTC, abeforgit commented
this is already behind a feature flag, so I think we can merge this

2021-09-01 15:34 UTC, merged