initial commit
lblod/ember-rdfa-editor pull request #256
Opened 2022-04-14 08:24 UTC by Asergey91

2022-04-22 11:45 UTC, Dietr approved these changes

2022-04-22 13:39 UTC, abeforgit requested changes

2022-04-22 13:39 UTC, abeforgit commented on addon/components/rdfa/plugin-wrapper.ts
> +export default class RdfaPluginWrapper extends Component<RdfaPluginWrapperArgs> {
The RdfaPluginWrapperArgs is not defined

2022-04-22 17:45 UTC, nvdk requested changes

2022-04-22 17:45 UTC, nvdk commented on addon/components/rdfa/rdfa-editor.hbs
> +          {{#if this.hasActiveHints}}
this block should be dropped (I think it's still there because of a faulty merge)

2022-04-22 17:45 UTC, nvdk commented on addon/components/rdfa/rdfa-editor.hbs
> +          {{#if this.suggestedHints.length}}
this block should be dropped, probably reintroduced in a faulty merge

2022-04-22 17:45 UTC, nvdk commented on app/helpers/is-insert-widget.js
> +export {
this is no longer used, so should be removed

2022-04-22 17:45 UTC, nvdk commented on app/helpers/not-insert-widget.js
> +export {
export of unexisting helper should be removed

2022-04-25 08:49 UTC, abeforgit approved these changes

2022-04-26 09:50 UTC, nvdk approved these changes
Looks good to me! I think we can merge and release this after the embeddable release. might take one more fix in the editor core before we can do that.

2022-04-27 14:47 UTC, merged