GN-4117: Correct cursor placement in ember node on select
lblod/ember-rdfa-editor pull request #693
Opened 2023-03-07 10:16 UTC by dkozickis

Looking for confirmation whether the plugin approach is correct?

https://user-images.githubusercontent.com/769698/223392664-5ecc4f93-27fe-4d44-8605-abb67dc7eeeb.mp4

2023-03-07 10:35 UTC, elpoelma commented
> Looking for confirmation whether the plugin approach is correct?

This is what we want indeed.

2023-03-08 11:38 UTC, elpoelma requested changes
Seems to work well at first glance :smile:. I just have some comments. As an alternative you could also look into the history plugin.

2023-03-08 11:38 UTC, elpoelma commented on addon/components/ember-node/embedded-editor.ts
> +      );
I think it's better to use `this.controller.mainEditorState` here. (To ensure this will also work with multi-level nested editors in the future).

2023-03-08 20:01 UTC, elpoelma commented on addon/components/ember-node/embedded-editor.ts
> +      );
Yes

2023-03-10 11:27 UTC, abeforgit commented
Ok for me once comments resolved

2023-03-10 13:25 UTC, elpoelma approved these changes

2023-03-10 13:25 UTC, merged