Resizable images
lblod/ember-rdfa-editor pull request #713
Opened 2023-03-15 10:54 UTC by elpoelma

This PR introduces the resizable images feature. Resizable images are implemented using an ember-node, when selected, handles are shown at the corners and sides of the image in order to resize it.

Specifically, this PR contains the following:
- A reworked `image` node-spec and an `image` node-view.
- The addition of an optional `stopEvent` attribute which can be provided when configuring an ember-node, it can be used to override the default behaviour of the `stopEvent` attribute of the ember-node node-view.

This PR is a solution to https://binnenland.atlassian.net/browse/GN-4142

2023-03-15 14:29 UTC, lagartoverde approved these changes
Looks good to me 👍

2023-03-15 18:32 UTC, usrtim approved these changes
LGTM

2023-03-16 10:14 UTC, elpoelma commented on addon/components/plugins/image/node.ts
> +      (key: HandleType) => this.handleReferences[key] === event.target
Yeah you're right, I will look if I find another way.

2023-03-16 10:21 UTC, elpoelma commented on addon/components/plugins/image/node.ts
> +      (key: HandleType) => this.handleReferences[key] === event.target
Improved it a bit :)

2023-03-20 13:33 UTC, abeforgit requested changes
the first time you use the left/right/top/bottom handles, the image resizes proportionally, the second time it doesn't

both ff and chrome

2023-03-22 08:14 UTC, merged