Feature/table tab handler
lblod/ember-rdfa-editor pull request #73
Opened 2021-03-30 15:01 UTC by lagartoverde

2021-03-31 07:02 UTC, nvdk requested changes
This was not properly tested outside of a table, it breaks the tab handler outside of tables.

2021-03-31 07:02 UTC, nvdk commented on addon/utils/plugins/table/tab-input-plugin.ts
> +    if(selection.isInTable) {
this is always truthful as it has the string "disabled" as value when disabled. As a result the tab handler executor will throw an error every time the plugin is called outside of a table

2021-03-31 07:18 UTC, nvdk commented
perhaps consider allowing the tab handler to jump out of the table when you press tab in the last cell?

2021-03-31 09:22 UTC, lagartoverde commented
Now the problem I see with allowing the table to go outside is that we cannot go inside, so it feels like the navigation is broken, maybe the solution is to fix the tab handler outside of the table to jump to the first cell when it encounters a table. I have uploaded the code so you can test what it happens

2021-03-31 15:13 UTC, nvdk approved these changes
Looks ok to me, in firefox at least it is jumping in the table as well. though perhaps not to where we want it to jump? This could be a further improvement.

2021-03-31 15:35 UTC, lagartoverde commented
In firefox it looks like it's jumping inside the table at the correct position but it's not if you press tab again it kinda breaks but I agree the objective of the task was to provide navigation inside the table we can fix that later on another task

2021-04-01 08:36 UTC, nvdk commented
@lagartoverde  can you resolve the merge conflicts and merge?

2021-04-01 09:42 UTC, merged